# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_person_father'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='sex',
            new_name='gender',
        ),
    ]
