# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0005_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='older_brother',
            field=models.ManyToManyField(to='listapp.Person'),
        ),
    ]
